Prompt update

diff --git a/.bash/prompt b/.bash/prompt
--- a/.bash/prompt
+++ b/.bash/prompt
@@ -7,6 +7,9 @@
 . ~/.bash/color
 
 function prompt_command() {
+
+        local last_status=$?
+        
 	GIT_PS1_SHOWDIRTYSTATE=1
 	GIT_PS1_SHOWSTASHSTATE=1
 	GIT_PS1_SHOWUNTRACKEDFILES=
@@ -14,27 +17,32 @@ function prompt_command() {
 	git_line=$(__git_ps1 '%s')
 
 	local -a ps1_lines
+
+        # Line 1
 	if [ "$EUID" = "0" ]; then # Root
-		ps1_lines+='\n\[${COLOR_RED_BOLD}\]\u\[${COLOR_NORM_BOLD}\]@\[${COLOR_YELLOW_BOLD}\]\h: \[${COLOR_NORM_BOLD}\]\[$PWD\]'
+		ps1_lines+='\n┌(\[${COLOR_RED_BOLD}\]\u\[${COLOR_BLUE}\]@\H\[${COLOR_NORM}\]) -- \[${COLOR_NORM}\]\[$PWD\]'
 	else
-		ps1_lines+='\n\[${COLOR_GREEN_BOLD}\]\u\[${COLOR_NORM_BOLD}\]@\[${COLOR_YELLOW_BOLD}\]\h: \[${COLOR_NORM_BOLD}\]\[$PWD\]'
+		ps1_lines+='\n┌(\[${COLOR_GREEN}\]\u\[${COLOR_BLUE}\]@\H\[${COLOR_NORM}\]) -- \[${COLOR_NORM}\]\[$PWD\]'
 	fi
 
+        # Line 2
 	if [ "" != "$git_line" ]; then # In a git repo
-		ps1_lines+='\n\[${COLOR_YELLOW_BOLD}\]$(__git_ps1 "[git: %s]")\[${COLOR_NORM_BOLD}\]'
+		ps1_lines+='\n├[\[${COLOR_YELLOW}\]$(__git_ps1 "git: %s")\[${COLOR_NORM}\]]'
 	fi
-
-	if [ "$EUID" = "0" ]; then # Root
-		#ps1_lines+='\n\[${COLOR_RED_BOLD}\]😡\[${COLOR_NORM}\] '
-		#ps1_lines+='\n\[${COLOR_RED_BOLD}\]👺\[${COLOR_NORM}\] '
-		#ps1_lines+='\n\[${COLOR_RED_BOLD}\]👹\[${COLOR_NORM}\] '
-		ps1_lines+='\n\[${COLOR_RED_BOLD}\]👀 \[${COLOR_NORM}\] '
-		#ps1_lines+='\n\[${COLOR_RED_BOLD}\]👒 \[${COLOR_NORM}\] '
-		#ps1_lines+='\n\[${COLOR_RED_BOLD}\]🙈 \[${COLOR_NORM}\] '
-		#ps1_lines+='\n\[${COLOR_RED_BOLD}\]😨 \[${COLOR_NORM}\] '
-	else
-		ps1_lines+='\n\[${COLOR_GREEN_BOLD}\]⚡\[${COLOR_NORM}\] '
-	fi
+        
+        # Line 3
+        # http://emojipedia.org/people/
+        if [ "0" == "$last_status" ]; then
+            faces=('\n└(😑 )→ ' '\n└(😎 )→ ' '\n└(😀 )→ ' '\n└(😉 )→ ' '\n└(😘 )→ ' '\n└(😇 )→ ' '\n└(😮 )→ ' '\n└(😪 )→ ' '\n└(😫 )→ ' '\n└(😜 )→ ' '\n└(😓 )→ ' '\n└(😜 )→ ' '\n└(😖 )→ ' '\n└(😤 )→ ' '\n└(😭 )→ ' '\n└(😦 )→ ' '\n└(😲 )→ ' '\n└(😨 )→ ' '\n└(😭 )→ ' '\n└(😱 )→ ')
+            ps1_lines+=${faces[$RANDOM % ${#faces[@]}]} # pick a random face
+        else
+            ps1_lines+='\n└(💀 )⤳ ' # Last script exited with a non-zero code
+            #ps1_lines+='\n└(🔴 )⤳ ' # Last script exited with a non-zero code
+            #ps1_lines+='\n└(‼️ )⤳ ' # Last script exited with a non-zero code
+            #ps1_lines+='\n└(❌ )⤳ ' # Last script exited with a non-zero code
+            #ps1_lines+='\n└(⛔ )⤳ ' # Last script exited with a non-zero code
+            #ps1_lines+='\n└(🚫 )⤳ ' # Last script exited with a non-zero code
+        fi
 
 	PS1="${ps1_lines[*]}"
 }
