save

diff --git a/common/kubectl b/common/kubectl
--- a/common/kubectl
+++ b/common/kubectl
@@ -26,7 +26,7 @@ fi
 __k8sctl() {
     now=$(date '+%s')
     diff=$((now - __KUBECONFIG_UPDATED_AT))
-    export __KUBECONFIG_UPDATED_AT=$(date '+%s')
+    eval "export __KUBECONFIG_UPDATED_AT=$now"
     if [ "$KUBECONFIG" != "$KUBECONFIG_DEFAULT" ] && [ "$__KUBECONFIG_TTL" -lt "$diff" ]; then
         (
             ORNG=$'\033[38;5;172m'
@@ -37,9 +37,9 @@ __k8sctl() {
         "
             exit 1
         )
-        export KUBECONFIG=$KUBECONFIG_DEFAULT
-        export K8S_CURRENT_CONTEXT=$(kubectl config view -o=jsonpath='{.current-context}')
-        export K8S_CURRENT_NAMESPACE=$(kubectl config view -o=jsonpath="{.contexts[?(@.name==\"$K8S_CURRENT_CONTEXT\")].context.namespace}")
+        eval "export KUBECONFIG=$KUBECONFIG_DEFAULT"
+        eval "export K8S_CURRENT_CONTEXT=$(kubectl config view -o=jsonpath='{.current-context}')"
+        eval "export K8S_CURRENT_NAMESPACE=$(kubectl config view -o=jsonpath=\"{.contexts[?(@.name==\\\"$K8S_CURRENT_CONTEXT\\\")].context.namespace}\")"
     else
         kubectl $@
     fi
@@ -79,17 +79,26 @@ kx() {
         eval "export KUBECONFIG=$__LAST_KUBECONFIG"
         eval "export __LAST_KUBECONFIG=$a"
     elif [ "" != "$1" ]; then
-        if [ -f "$HOME/.kube/$1/config.vault" ]; then
+        conf_path="$HOME/.kube/$1"
+        cluster=$1
+        if [ -L "$HOME/.kube/$1" ]; then
+            conf_path=$(readlink "$HOME/.kube/$1")
+            cluster=$(basename $conf_path)
+        fi
+
+        eval $(aquaduck auth kube $cluster --k8s-auth-type kops)
+
+        if [ -f "$HOME/.kube/$conf_path/config.vault" ]; then
             eval "export __LAST_KUBECONFIG=$KUBECONFIG"
-            eval "export KUBECONFIG=$HOME/.kube/$1/config.vault"
-        elif [ -f "$HOME/.kube/$1/config" ]; then
+            eval "export KUBECONFIG=$HOME/.kube/$conf_path/config.vault"
+        elif [ -f "$HOME/.kube/$conf_path/config" ]; then
             eval "export __LAST_KUBECONFIG=$KUBECONFIG"
-            eval "export KUBECONFIG=$HOME/.kube/$1/config"
-        elif [ -f "$HOME/.kube/$1/config.kops" ]; then
+            eval "export KUBECONFIG=$HOME/.kube/$conf_path/config"
+        elif [ -f "$HOME/.kube/$conf_path/config.kops" ]; then
             eval "export __LAST_KUBECONFIG=$KUBECONFIG"
-            eval "export KUBECONFIG=$HOME/.kube/$1/config.kops"
+            eval "export KUBECONFIG=$HOME/.kube/$conf_path/config.kops"
         else
-            >&2 echo "File not found: $HOME/.kube/$1/config"
+            >&2 echo "File not found: $HOME/.kube/$conf_path/config"
             return 1
         fi
     else
@@ -97,17 +106,17 @@ kx() {
         eval "export KUBECONFIG=$KUBECONFIG_DEFAULT"
     fi
     if [ "$KUBECONFIG_DEFAULT" != "$KUBECONFIG" ]; then
-        export __KUBECONFIG_UPDATED_AT=$(date '+%s')
+        eval "export __KUBECONFIG_UPDATED_AT=$(date '+%s')"
     fi
     K8S_CURRENT_CONTEXT=$(kubectl config view -o=jsonpath='{.current-context}')
     eval "export K8S_CURRENT_CONTEXT=$K8S_CURRENT_CONTEXT"
     eval "export K8S_CURRENT_NAMESPACE=$(kubectl config view -o=jsonpath="{.contexts[?(@.name==\"$K8S_CURRENT_CONTEXT\")].context.namespace}")"
     K8S_LAST_NAMESPACE[$K8S_CURRENT_CONTEXT]=$K8S_CURRENT_NAMESPACE
-    export -A K8S_LAST_NAMESPACE
+    eval "export -A K8S_LAST_NAMESPACE"
 
     if [ "" != "${K8S_NAMESPACES[$K8S_CURRENT_CONTEXT]}" ]; then
         K8S_NAMESPACES[$K8S_CURRENT_CONTEXT]=$(kubectl get namespaces | grep -vE 'NAME.*STATUS.*AGE.*' | awk '{print $1}')
-        export -A K8S_NAMESPACES
+        eval "export -A K8S_NAMESPACES"
     fi
 }
 export -f kx
@@ -137,15 +146,11 @@ kn() {
 }
 export -f kn
 
-# kx context autocompletion. K8S_STATUS_LINE_CONTEXTS should be a
-# space-delimited list of context names.
-if [ "" = "$K8S_STATUS_LINE_CONTEXTS" ]; then
-    export K8S_STATUS_LINE_CONTEXTS="$(find $HOME/.kube/ -name config)"
-fi
+# kx context autocompletion.
 __completeKx() {
     cur="${COMP_WORDS[COMP_CWORD]}"
-    cmds=$K8S_STATUS_LINE_CONTEXTS
-    COMPREPLY=($(compgen -d -f -W "$cmds" -- $cur))
+    cmds="$(env ls -1 /Users/mkenney/.kube/ | sort)"
+    COMPREPLY=($(compgen -f -W "$cmds" -- $cur))
     return 0
 }
 complete -F __completeKx kx
@@ -159,7 +164,7 @@ fi
 __completeKn() {
     cur="${COMP_WORDS[COMP_CWORD]}"
     cmds=${K8S_NAMESPACES[$K8S_CURRENT_CONTEXT]}
-    COMPREPLY=($(compgen -d -f -W "$cmds" -- $cur))
+    COMPREPLY=($(compgen -f -W "$cmds" -- $cur))
     return 0
 }
 complete -F __completeKn kn
@@ -169,7 +174,8 @@ complete -F __completeKn kn
 # ⎈ docker-for-desktop/default
 __k8s_status() {
     if [ "enabled" = "$K8S_STATUS_LINE" ]; then
-        echo $K8S_PS1_SYMBOL $K8S_CURRENT_CONTEXT/$(kn)
+        now=$(date '+%s')
+        echo "$K8S_PS1_SYMBOL $K8S_CURRENT_CONTEXT/$(kn)"
     fi
 }
 if [ "" = "$K8S_PS1_SYMBOL" ]; then
