Refactoring to suppor both bash and zsh (wip)

diff --git a/zsh/prompt b/zsh/prompt
--- a/zsh/prompt
+++ b/zsh/prompt
@@ -1,47 +1,15 @@
 #!/bin/zsh
 
-## Find my full .zshrc at <github.com/mislav/dotfiles/blob/master/zshrc>.
-
 # setup
-
 autoload -U colors && colors
 export LSCOLORS="ExGxcxdxcxegedcbcdacad"
 setopt prompt_subst
-source ~/.dotfiles/resources/color
-
-# prompt
-
-#ZSH_THEME_GIT_PROMPT_PREFIX="%{$reset_color%}%{$fg[green]%}["
-#ZSH_THEME_GIT_PROMPT_SUFFIX="]%{$reset_color%}"
-#ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[red]%}*%{$reset_color%}"
-#ZSH_THEME_GIT_PROMPT_CLEAN=""
+source ~/.dotfiles/common/color
 
 GIT_PS1_SHOWDIRTYSTATE=1
 GIT_PS1_SHOWSTASHSTATE=1
 GIT_PS1_SHOWUNTRACKEDFILES=
 GIT_PS1_SHOWUPSTREAM=1
-#git_line=$(__git_ps1 '%s')
-last_status=$?
-
-# show git branch/tag, or name-rev if on detached head
-parse_git_branch() {
-  (command git symbolic-ref -q HEAD || command git name-rev --name-only --no-undefined --always HEAD) 2>/dev/null
-}
-
-# show red star if there are uncommitted changes
-parse_git_dirty() {
-  if command git diff-index --quiet HEAD 2> /dev/null; then
-    echo "$ZSH_THEME_GIT_PROMPT_CLEAN"
-  else
-    echo "$ZSH_THEME_GIT_PROMPT_DIRTY"
-  fi
-}
-
-# if in a git repo, show dirty indicator + git branch
-git_custom_status() {
-  local git_where="$(parse_git_branch)"
-  [ -n "$git_where" ] && echo "$(parse_git_dirty)$ZSH_THEME_GIT_PROMPT_PREFIX${git_where#(refs/heads/|tags/)}$ZSH_THEME_GIT_PROMPT_SUFFIX"
-}
 
 # put fancy stuff on the right
 #RPS1=`date "+%Y-%m-%d"`
@@ -52,15 +20,11 @@ git_custom_status() {
 __prompt_uid() {
     if [ "$EUID" = "0" ]; then # Root
         echo "
-┌(${COLOR_RED_BLINK}%n${COLOR_YELLOW}@%M${COLOR_NORM}) - ${COLOR_NORM}%/${COLOR_NORM}"
+┌(%{$COLOR_RED_BLINK%}%n%{$COLOR_YELLOW%}@%M%{$COLOR_NORM%}) - %{$COLOR_NORM%}%/%{$COLOR_NORM%}"
     else
         echo "
-┌(${COLOR_GREEN}%n${COLOR_YELLOW}@%M${COLOR_NORM}) - ${COLOR_NORM}%/${COLOR_NORM}"
+┌(%{$COLOR_GREEN%}%n%{$COLOR_YELLOW%}@%M%{$COLOR_NORM%}) - %{$COLOR_NORM%}%/%{$COLOR_NORM%}"
     fi
-}
-
-__git_untracked() {
-    echo $(git ls-files -o -d --exclude-standard | sed q | wc -l)
 }
 
 __git_status() {
@@ -82,12 +46,12 @@ __git_status() {
     local branch_name=$(git rev-parse --abbrev-ref HEAD)
 
     if [ "" != "$(git rev-list origin..HEAD)" ]; then
-        ahead_str=">$(git rev-list origin..HEAD | wc | awk '{print $1}')"
+        ahead_str=">$(git rev-list origin..HEAD 2> /dev/null | wc | awk '{print $1}')"
         output=1
     fi
 
     if [ "" != "$(git rev-list HEAD..origin)" ]; then
-        behind_str="$(git rev-list HEAD..origin | wc | awk '{print $1}')<"
+        behind_str="$(git rev-list HEAD..origin 2> /dev/null | wc | awk '{print $1}')<"
         output=1
     fi
 
@@ -156,22 +120,27 @@ __prompt_git() {
     if [ "" != "$(git rev-parse --git-dir 2> /dev/null)" ]; then
 
         echo "
-├[%{${COLOR_BLUE_FADED}%}git: $branch$(__git_status)%{${COLOR_NORM}%}]"
+├[%{$COLOR_BLUE_FADED%}git: $branch$(__git_status)%{$COLOR_NORM%}]"
     fi
 }
 
 __prompt_cmd() {
+    last_status=$1
     if [ "0" = "$last_status" ]; then
         echo "
-└(%{${COLOR_GREEN}%}%*%{${COLOR_NORM}%})%F{240}(zsh)%f→ "
+└(%{$COLOR_GREEN%}%*%{$COLOR_NORM%})%{%F{240}%}(zsh)%{%f%}→ "
     else
         echo "
-└(💀 )%{%F{240}%}(zsh)%{${COLOR_NORM}%}⤳ " # Last script exited with a non-zero code
+└(💀 )%{%F{240}%}(zsh)%{$COLOR_NORM%}⤳ " # Last script exited with a non-zero code
     fi
 }
 __zsh_prompt() {
-    echo "$ps1_lines"
+    # Make the cursor a blinking vertical line
+    # http://stackoverflow.com/questions/4416909/anyway-change-the-cursor-vertical-line-instead-of-a-box
+    last_status=$?
+    echo "$(__prompt_uid)$(__prompt_git)$(__prompt_cmd $last_status)$(echo -e -n "\x1b[\x35 q")"
 }
+
 # basic prompt on the left
 #PROMPT=$ps1_lines
-PROMPT='$(__prompt_uid)$(__prompt_git)$(__prompt_cmd)'
+PROMPT='$(__zsh_prompt)'
